services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5242:5242"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=StudentDB;User=FadyD;Password=Fady123;

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Fady1234"
      ACCEPT_EULA: "Fady"
    ports:
      - "7114:7114"
